@api = http://localhost:3020/api/v1/listas-precios

###GET ALERTAS
GET {{api}}/9001-000000000001/alertas

###POST ALERTA ITEM
POST {{api}}/9001-000000000001/alertas
Content-Type: application/json

{
  "Activo": "S",
  "Borrado": "N",
  "fecha": "2024-12-02T00:00:00.000Z",
  "reporte": true,
  "mensaje": "La lista de precios expira el 12 de diciembre.",
  "detail_row_reg": [
    {
      "_id": "67156acabc57b06756104d6b",
      "FechaReg": "2024-10-15T00:00:00.628Z",
      "UsuarioReg": "DRARAMIS"
    }
  ]
}

###POST ALERTAS LISTA
POST {{api}}/9001-000000000001/alertas-lista
Content-Type: application/json

[
  {
    "_id": "3",
    "Activo": "S",
    "Borrado": "N",
    "fecha": "2024-12-03T00:00:00.000Z",
    "reporte": true,
    "mensaje": "La lista de precios expira el 3 de diciembre.",
    "detail_row_reg": [
      {
        "_id": "67156acabc57b06756104d6c",
        "FechaReg": "2024-10-16T00:00:00.628Z",
        "UsuarioReg": "DRARAMIS"
      }
    ]
  },
  {
    "_id": "4",
    "Activo": "S",
    "Borrado": "N",
    "fecha": "2024-12-04T00:00:00.000Z",
    "reporte": true,
    "mensaje": "La lista de precios expira el 4 de diciembre.",
    "detail_row_reg": [
      {
        "_id": "67156acabc57b06756104d6d",
        "FechaReg": "2024-10-17T00:00:00.628Z",
        "UsuarioReg": "DRARAMIS"
      }
    ]
  }
]
###PUT ALERTAS ITEM
PUT {{api}}/9001-000000000001/alertas/3
Content-Type: application/json

{
  "_id": "1",
  "Activo": "S",
  "Borrado": "N",
  "fecha": "2024-12-04T00:00:00.000Z",
  "mensaje": "La lista de precios xpira el 10 de diciembre."
}

###DELETE ALERTAS ITEM
DELETE {{api}}/9001-000000000001/alertas/3